### ISSUE TITLE
Thoughts on moving away from Roboguice

### ISSUE THREAD

**Issue by Pho3niX90** [pires/android-obd-reader#130]
What are your thoughts?

I just personally think the less unnecessary library's that are used, the better the app will respond. Native android code has better performance

**Comment by pires** [comment]
I will not remove roboguice in favor of more boilerplate code.

**Comment by Hippoish24** [comment]
What responsiveness would removing Roboguice add?  As I understand it, it's only used when initializing the app for creating the UI elements.

**Comment by pires** [comment]
@Hippoish24 it's also helping a lot with service and `AsyncTask` lifecycle management. Again, this is a no-go for me unless something happens to how much Android code we need to handle this burden.

**Comment by Pho3niX90** [comment]
@Hippoish24 http://developer.android.com/training/articles/memory.html#DependencyInjection

If you really need to use a framework I would say use http://google.github.io/dagger/

**Comment by amouly** [comment]
+1 for Dagger.

**Comment by pires** [comment]
Dagger is much more complicated to use and I want to maintain the app simple. I don't see any added value for the user in this, since the application delivers what it's supposed to do.

Still, I'm open to analyze a PR that replaces Roboguice with something that means more performance **AND** less code.
